# Generated by Django 4.2.11 on 2024-05-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_name", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=100)),
                ("service_status", models.CharField(max_length=100)),
                ("next_service_date", models.DateField(blank=True, null=True)),
                ("registration_renewal_date", models.DateField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
