# Generated by Django 5.0.4 on 2024-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_name", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=100)),
                ("service_status", models.CharField(max_length=100)),
                ("next_service_date", models.DateField(blank=True, null=True)),
                ("registration_renewal_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
