# Generated by Django 5.0.4 on 2024-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0006_employee_farm"),
        ("farm", "0002_setup_default_farm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("email", "contactNumber", "farm")},
        ),
    ]
