# Generated by Django 5.0.4 on 2024-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0002_alter_inventoryitem_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("needs repair", "Needs Repair"),
                    ("service due", "Service Due"),
                ],
                max_length=20,
            ),
        ),
    ]
