# Generated by Django 5.0.4 on 2024-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_management", "0003_alter_inventoryitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("seeds", "Seeds"),
                    ("fertilizers", "Fertilizers"),
                    ("feed", "Feed"),
                    ("tools", "Tools"),
                    ("machinery", "Machinery"),
                    ("vehicles", "Vehicles"),
                ],
                max_length=50,
            ),
        ),
    ]
