# Generated by Django 5.0.4 on 2024-05-06 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
        ("inventory_management", "0004_alter_inventoryitem_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="farm",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="farm.farm",
            ),
            preserve_default=False,
        ),
    ]
