# Generated by Django 5.0.4 on 2024-05-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendarevent",
            name="task",
        ),
    ]
