# Generated by Django 5.0.4 on 2024-05-06 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0002_remove_calendarevent_task"),
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="farm",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="farm.farm",
            ),
            preserve_default=False,
        ),
    ]
