# Generated by Django 5.0.4 on 2024-05-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0010_task_due_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
