# Generated by Django 5.0.4 on 2024-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0007_alter_vehicleitem_image_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleitem',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleitem',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleitem',
            name='vehicle_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
