# Generated by Django 5.0.4 on 2024-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('size_acers', models.CharField(max_length=50)),
                ('section_type', models.CharField(max_length=100)),
                ('add_info', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
