# Generated by Django 4.2.11 on 2024-05-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("size_acers", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("crop", "Crop"),
                            ("livestock", "Livestock"),
                            ("field", "Field"),
                            ("barn", "Barn"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("add_info", models.CharField(blank=True, max_length=255)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
