# Generated by Django 5.0.4 on 2024-05-12 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_invitationcode_customuser_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_owner": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitationcode",
            name="for_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitationcode",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_owner": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitation_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
