# Generated by Django 4.2.11 on 2024-05-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("section_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
